language: node_js

node_js:
  - "12.16.1"

cache:
  directories:
    - node_modules

services:
  - docker

install:
  - npm ci

script:
  - npm run lint
  - npm run test
  - if [[ -z $TRAVIS_TAG ]]; then docker build -t shlink-website:test . ; fi

deploy:
  - provider: script
    script: bash ./scripts/docker/build
    on:
      condition: $TRAVIS_PULL_REQUEST == 'false'
