language: node_js

node_js:
  - "10.16.3"

cache:
  directories:
    - node_modules

services:
  - docker

install:
  - npm ci

script:
  - npm run lint
  - npm run test
  - if [[ -z $TRAVIS_TAG ]]; then docker build -t shlink-website:test . ; fi
