name: Check external links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  markdown-link-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: 'yes'
          folder-path: './src/content'
          file-extension: '.mdx'
